services:
  database:
    image: pgvector/pgvector:pg16
    shm_size: 256mb
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      my-network:

volumes:
  db_data:

networks:
  my-network:
    driver: bridge
